- name: Add an apt key by id for erlang
  apt_key:
    keyserver: "{{ erlang_apt_repo_gpgkey_server }}"
    id: "{{ erlang_apt_repo_gpgkey_id }}"
    state: present

- name: Add apt repository for erlang
  apt_repository:
    repo: "{{ erlang_apt_repo_url }}"
    filename: rabbitmq_erlang
    update_cache: no

- name: Set package erlang preference
  copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: release o=Bintray
      Pin-Priority: 1000

- name: Add an apt key by id for rabbitmq
  apt_key:
    keyserver: "{{ rabbitmq_apt_repo_gpgkey_server }}"
    id: "{{ rabbitmq_apt_repo_gpgkey_id }}"
    state: present

- name: Add apt repository for rabbitmq
  apt_repository:
    repo: "{{ rabbitmq_apt_repo_url }}"
    filename: rabbitmq_main
    update_cache: yes

- name: Install RabbitMQ
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    state: present
    # Prevent Rabbit from starting immediately after installation before we could apply custom config (including clustering)
    policy_rc_d: 101 # 101 means "action forbidden by policy"
  notify: restart rabbitmq-server
